events:
  baseeventtype:
    properties:
      source:
        type: string
      id:
        type: string
      time:
        type: string
      schemaurl:
        type: string
        pattern: '\w+:(\/?\/?)[^\s]+'
      contenttype:
        type: string
      data:
        AnyValue: {}
    required:
      - source
      - id