events:
  exampleCloudEvent:
    attributes:
      # You may remove the specifications for attribute id, source, specversion,
      # and type below. Cloud Event Generator will add them as shown below
      # automatically if they are not present.
      id:
        type: string
        format: uuid
        auto: true
        minLength: 1
      source:
        type: string
        format: uri-reference
      specversion:
        type: string
        enum:
          - "0.3"
        default: "0.3"
      type:
        type: string
        minLength: 1
    required:
      - id
      - source
      - specversion
      - type
metadata:
  packageName: mypackage
  version: "0.0.1"